#pragma once

// Essentially a copy of the Linux x86 errno.h, pared back to just error codes
// I expect to be used in this kernel
typedef enum errno {
    ESUCCESS        = 0x00, // Success
    EPERM           = 0x01, // Operation not permitted
    ENOENT          = 0x02, // No such file or directory
    ESRCH           = 0x03, // No such process
    EINTR           = 0x04, // Interrupted system call
    EIO             = 0x05, // I/O error
    ENXIO           = 0x06, // No such device or address
    E2BIG           = 0x07, // Argument list too long
    ENOEXEC         = 0x08, // Exec format error
    EBADF           = 0x09, // Bad file number
    ECHILD          = 0x0A, // No child processes
    EAGAIN          = 0x0B, // Try again
    ENOMEM          = 0x0C, // Out of memory
    EACCES          = 0x0D, // Permission denied
    EFAULT          = 0x0E, // Bad address
    ENOTBLK         = 0x0F, // Block device required
    EBUSY           = 0x10, // Device or resource busy
    EEXIST          = 0x11, // File exists
    EXDEV           = 0x12, // Cross-device link
    ENODEV          = 0x13, // No such device
    ENOTDIR         = 0x14, // Not a directory
    EISDIR          = 0x15, // Is a directory
    EINVAL          = 0x16, // Invalid argument
    ENFILE          = 0x17, // File table overflow
    EMFILE          = 0x18, // Too many open files
    ENOTTY          = 0x19, // Not a typewriter
    ETXTBSY         = 0x1A, // Text file busy
    EFBIG           = 0x1B, // File too large
    ENOSPC          = 0x1C, // No space left on device
    ESPIPE          = 0x1D, // Illegal seek
    EROFS           = 0x1E, // Read-only file system
    EMLINK          = 0x1F, // Too many links
    EPIPE           = 0x20, // Broken pipe
    EDOM            = 0x21, // Math argument out of domain of func
    ERANGE          = 0x22, // Math result not representable
    EDEADLK         = 0x23, // Resource deadlock would occur
    ENAMETOOLONG    = 0x24, // File name too long
    ENOLCK          = 0x25, // No record locks available
    ENOSYS          = 0x26, // Function not implemented
    ENOTEMPTY       = 0x27, // Directory not empty
    ELOOP           = 0x28, // Too many symbolic links encountered
    ERRNO_UNUSED_41 = 0x29, // Unused error number
    ENOMSG          = 0x2A, // No message of desired type
    EIDRM           = 0x2B, // Identifier removed
    ECHRNG          = 0x2C, // Channel number out of range
    EL2NSYNC        = 0x2D, // Level 2 not synchronized
    EL3HLT          = 0x2E, // Level 3 halted
    EL3RST          = 0x2F, // Level 3 reset
    ELNRNG          = 0x30, // Link number out of range
    EUNATCH         = 0x31, // Protocol driver not attached
    ENOCSI          = 0x32, // No CSI structure available
    EL2HLT          = 0x33, // Level 2 halted
    EBADE           = 0x34, // Invalid exchange
    EBADR           = 0x35, // Invalid request descriptor
    EXFULL          = 0x36, // Exchange full
    ENOANO          = 0x37, // No anode
    EBADRQC         = 0x38, // Invalid request code
    EBADSLT         = 0x39, // Invalid slot
    EDEADLOCK       = 0x3A, // File locking deadlock error
    EBFONT          = 0x3B, // Bad font file format
    ENOSTR          = 0x3C, // Device not a stream
    ENODATA         = 0x3D, // No data available
    ETIME           = 0x3E, // Timer expired
    ENOSR           = 0x3F, // Out of streams resources
    ENONET          = 0x40, // Machine is not on the network
    ENOPKG          = 0x41, // Package not installed
    EREMOTE         = 0x42, // Object is remote
    ENOLINK         = 0x43, // Link has been severed
    EADV            = 0x44, // Advertise error
    ESRMNT          = 0x45, // Srmount error
    ECOMM           = 0x46, // Communication error on send
    EPROTO          = 0x47, // Protocol error
    EMULTIHOP       = 0x48, // Multihop attempted
    EDOTDOT         = 0x49, // RFS specific error
    EBADMSG         = 0x4A, // Not a data message
    EOVERFLOW       = 0x4B, // Value too large for defined data type
    ENOTUNIQ        = 0x4C, // Name not unique on network
    EBADFD          = 0x4D, // File descriptor in bad state
    EREMCHG         = 0x4E, // Remote address changed
    ELIBACC         = 0x4F, // Can not access a needed shared library
    ELIBBAD         = 0x50, // Accessing a corrupted shared library
    ELIBSCN         = 0x51, // .lib section in a.out corrupted
    ELIBMAX         = 0x52, // Attempting to link in too many shared libraries
    ELIBEXEC        = 0x53, // Cannot exec a shared library directly
    EILSEQ          = 0x54, // Illegal byte sequence
    ERESTART        = 0x55, // Interrupted system call should be restarted
    ESTRPIPE        = 0x56, // Streams pipe error
    EUSERS          = 0x57, // Too many users
    ENOTSOCK        = 0x58, // Socket operation on non-socket
    EDESTADDRREQ    = 0x59, // Destination address required
    EMSGSIZE        = 0x5A, // Message too long
    EPROTOTYPE      = 0x5B, // Protocol wrong type for socket
    ENOPROTOOPT     = 0x5C, // Protocol not available
    EPROTONOSUPPORT = 0x5D, // Protocol not supported
    ESOCKTNOSUPPORT = 0x5E, // Socket type not supported
    EOPNOTSUPP      = 0x5F, // Operation not supported on transport endpoint
    EPFNOSUPPORT    = 0x60, // Protocol family not supported
    EAFNOSUPPORT    = 0x61, // Address family not supported by protocol
    EADDRINUSE      = 0x62, // Address already in use
    EADDRNOTAVAIL   = 0x63, // Cannot assign requested address
    ENETDOWN        = 0x64, // Network is down
    ENETUNREACH     = 0x65, // Network is unreachable
    ENETRESET       = 0x66, // Network dropped connection because of reset
    ECONNABORTED    = 0x67, // Software caused connection abort
    ECONNRESET      = 0x68, // Connection reset by peer
    ENOBUFS         = 0x69, // No buffer space available
    EISCONN         = 0x6A, // Transport endpoint is already connected
    ENOTCONN        = 0x6B, // Transport endpoint is not connected
    ESHUTDOWN       = 0x6C, // Cannot send after transport endpoint shutdown
    ETOOMANYREFS    = 0x6D, // Too many references: cannot splice
    ETIMEDOUT       = 0x6E, // Connection timed out
    ECONNREFUSED    = 0x6F, // Connection refused
    EHOSTDOWN       = 0x70, // Host is down
    EHOSTUNREACH    = 0x71, // No route to host
    EALREADY        = 0x72, // Operation already in progress
    EINPROGRESS     = 0x73, // Operation now in progress
    ESTALE          = 0x74, // Stale file handle
    EUCLEAN         = 0x75, // Structure needs cleaning
    ENOTNAM         = 0x76, // Not a XENIX named type file
    ENAVAIL         = 0x77, // No XENIX semaphores available
    EISNAM          = 0x78, // Is a named type file
    EREMOTEIO       = 0x79, // Remote I/O error
    EDQUOT          = 0x7A, // Quota exceeded
    ENOMEDIUM       = 0x7B, // No medium found
    EMEDIUMTYPE     = 0x7C, // Wrong medium type
    ECANCELED       = 0x7D, // Operation Canceled
    ENOKEY          = 0x7E, // Required key not available
    EKEYEXPIRED     = 0x7F, // Key has expired
    EKEYREVOKED     = 0x80, // Key has been revoked
    EKEYREJECTED    = 0x81, // Key was rejected by service
    EOWNERDEAD      = 0x82, // Owner died
    ENOTRECOVERABLE = 0x83, // State not recoverable
    ERFKILL         = 0x84, // Operation not possible due to RF-kill
    EHWPOISON       = 0x85, // Memory page has hardware error

    // Linux aliases for common cases
    EWOULDBLOCK     = EAGAIN,      // Operation would block
    ENOTSUP         = EOPNOTSUPP   // Not supported
} errno_t;

extern const char* errno_to_string(errno_t err);
